- name: create jenkins job
  hosts: local
  state: local
  tasks:
    - name: Create a jenkins job
      community.general.jenkins_job:
        config: "{{ lookup('file', 'test.xml') }}"
        name: test job by ansible
        password: admin123
        url: http://172.31.38.225:8080
        user: admin
