- name: Check if the job exists or not
  community.general.jenkins_job_info:
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.38.225:8080
    user: admin
  register: my_jenkins_job_status

#- name: debug
#  debug:
#    msg: "{{ my_jenkins_job_status }}"

- name: Copy Xml File
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml
  when: my_jenkins_job_status.failed

- name: Create Jenkins Jobs
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.38.225:8080
    user: admin
  when: my_jenkins_job_status.failed